name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo ${{ vars.SECRET1 }}
      - run: echo ${{ secrets.SECRET1 }}
      - run: echo ${{ vars.MY_ENV1 }}
