name: Deployment
run-name: '[${{ github.event.inputs.environment }}][${{github.ref_name}}] Continuous Deployment'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["", "-0210", "-9143"]
    environment: ${{ github.event.inputs.environment }}${{ matrix.environment }}
    steps:
      - run: echo ${{ vars.SECRET1 }}
      - run: echo ${{ secrets.SECRET1 }}
      - run: echo ${{ vars.MY_ENV1 }}
      - name: print secrets
        run: |
            mkdir -p src
            touch src/.env
            echo $DEV_ENV_FILE >> src/.env
            cat src/.env
        shell: bash
        env:
          DEV_ENV_FILE : ${{secrets.SECRET1}}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
         name: ${{ github.event.inputs.environment }}-${{ matrix.environment }}
         path: src/.env
