name: Deployment
run-name: '[${{ github.event.inputs.environment }}][${{github.ref_name}}] Continuous Deployment'

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo ${{ vars.SECRET1 }}
      - run: echo ${{ secrets.SECRET1 }}
      - run: echo ${{ vars.MY_ENV1 }}
      - name: print secrets
        run: |
            mkdir src
            touch src/.env
            echo $DEV_ENV_FILE >> src/.env
            cat src/.env
        shell: bash
        env:
          DEV_ENV_FILE : ${{secrets.SECRET1}}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
         name: DEV_ENV_FILE
         path: src/.env
