name: Extract JSON Keys and Use in Matrix

on: [push]

jobs:
  extract-bank-codes:
    runs-on: ubuntu-latest
    environment: production

    outputs:
      keys: ${{ steps.extract_bank_codes.outputs.codes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read and extract JSON keys
        id: extract_bank_codes
        run: |
          # Read JSON-formatted AWS_BUCKET_NAME
          buckets_json='${{vars.AWS_BUCKET_NAME}}'
          
          # Extract bank codes and convert to a JSON array
          bank_codes=$(echo "$buckets_json" | jq -c 'keys')

          echo "bank codes: $bank_codes"

          # Set the bank code array as an output
          echo "::set-output name=codes::$bank_codes"

  use-keys:
    needs: extract-bank-codes
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        key: ${{ fromJson(needs.extract-bank-codes.outputs.codes) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use extracted keys
        run: |
          echo "Key: ${{ matrix.key }}"
          
          json_content='${{vars.AWS_BUCKET_NAME}}'
          
          # Extract the value for the current key
          key=${{ matrix.key }}
          value=$(echo "$json_content" | jq -r ".\"$key\"")
          echo "value"
          echo $value
